version: 2.1

aliases:
  - &defaults
    docker:
      - image: cimg/node:16.14.2-browsers
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    working_directory: ~/repo

jobs:
  build-and-deploy-staging:
    <<: *defaults
    steps:
      - run: "false"
  build-and-deploy-production:
    <<: *defaults
    steps:
      - run: "false"

workflows:
  build-test-deploy:
    jobs:
      - build-and-deploy-staging:
          context:
            - scratch-www-all
            - scratch-www-staging
            - dockerhub-credentials
      - build-and-deploy-production:
          context:
            - scratch-www-all
            - scratch-www-production
            - dockerhub-credentials
